# Where things are
layouts:     ./_layouts

# Handling Reading
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

permalink: /:year-:month/:title/
markdown: redcarpet
highlighter: pygments
paginate: 5

# Markdown Processors
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "with_toc_data", "tables", "highlight", "footnotes"]

kramdown:
  input: GFM
  #Insert HTML <br /> tags inside paragraphs where the original Markdown document had newlines (by default, Markdown ignores these newlines). default is true. Github is false.
  hard_wrap: false

title: HuangWei's blog

# mainland-cdn
cdn:
  link: http://dn-huangweipro.qbox.me

comments :
  provider : duoshuo
  duoshuo : 
    short_name : huangweipro
